apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: dojot_prom
  name: dojot_prom
spec:
  endpoints:
  - interval: 1s
    port: http
  selector:
    matchLabels:
      name: dojot_prom
