# prometheus.yml
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['172.17.0.2:3000']
        labels:
          service: 'test-prom'
          group: 'production'