apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dojot-prom
  namespace: dojot
spec:
  endpoints:
  - interval: 2s
    port: http
  selector:
    matchLabels:
      app: dojot-prom
