## This role is responsible for deploying Kong for dojot

- name: dojot - verneMQ mqtt_bridge Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'mqtt_bridge_cluster_cluster.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'mqtt_bridge_service.yaml.j2') | from_yaml }}"