version: '3'
services:
  vmq-dojot:
    image: mprevide/verne
    ports:
      - 1883:1883
      - 8883:8883
    environment:
      CERT_EJBCA_API_BROKER: "ejbca_simple"
      CERT_EJBCA_API_PORT: "5583"
      STATIC_CERT: "n"
      K8S_ENV: "n"
      HOSTNAME: "broker"
      CERT_DNS: "192.168.96.1"
      CRL_UPDATE_TIME: "*/30 * * * *" #every 30 min
      CHECK_EXPIRATION_TIME:  "*/30 * * * *" #every 30 min
      CHECKEND_EXPIRATION_SEC: '43200' #12h
      DOCKER_VERNEMQ_LOG__CONSOLE: "both"
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: "debug"
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS: "on"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_REGISTER__HOOK: "auth_on_register"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_REGISTER__ENDPOINT: "http://webhook-verne:4000/reg"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_PUBLISH__HOOK: "auth_on_publish"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_PUBLISH__ENDPOINT: "http://webhook-verne:4000/pub"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_SUBSCRIBE__HOOK: "auth_on_subscribe"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_SUBSCRIBE__ENDPOINT: "http://webhook-verne:4000/sub"
      #DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_UNSUBSCRIBE__HOOK: "on_unsubscribe"
      #DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_UNSUBSCRIBE__ENDPOINT: "http://webhook:4000/unsub"
      #DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_DELIVER__HOOK: "on_deliver"
      #DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_DELIVER__ENDPOINT: "http://webhook:4000/deliver"
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT: "0.0.0.0:8883"
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__USE_IDENTITY_AS_USERNAME: "off"
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__REQUIRE_CERTIFICATE: "on"
      DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: /vernemq/cert/ca.crt
      DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: /vernemq/cert/broker.crt
      DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: /vernemq/cert/broker.key
      DOCKER_VERNEMQ_LISTENER__SSL__CRLFILE: /vernemq/cert/ca.crl

  ejbca_simple:
    image: mprevide/ejbca
    depends_on:
      - postgres_ejbca
    ports:
      - 5583:5583
    hostname: localhost
    restart: always
    environment:
      DATABASE_JDBC_URL: "jdbc:postgresql://postgres_ejbca/ejbca_db"
      DATABASE_USER: "youruser"
      DATABASE_PASSWORD: "yourpassword"
      LOG_LEVEL_APP: "ERROR"
      LOG_LEVEL_SERVER_SUBSYSTEMS: "ERROR"
      LOG_LEVEL_APP_WS_TRANSACTIONS: "ERROR"
      LOG_LEVEL_SERVER: "ERROR"
      LOG_LEVEL_APP_OCSP_TRANSACTIONS: "ERROR"

  postgres_ejbca:
    image: library/postgres
    restart: always
    environment:
      POSTGRES_USER: "youruser"
      POSTGRES_PASSWORD: "yourpassword"
      POSTGRES_DB: "ejbca_db"


  webhook-verne:
    image: mprevide/webhook_verne
    restart: always
    environment:
      VERNE_WEBHOOKS_PORT: "4000"
      VERNE_WEBHOOKS_LOG_LEVEL: "debug"
