version: '3'
services:
  vmq-dojot:
    image: mprevide/verne
    ports:
      - 1883:1883
      - 8883:8883
    environment:
      CERT_EJBCA_API_BROKER: "ejbca_simple"
      CERT_EJBCA_URL: "5583"
      STATIC_CERT: "n"
      K8S_ENV: "n"
      HOSTNAME: "broker"
      CRL_UPDATE_TIME: "* * * * *" #every 10 min "*/10 * * * *"
      CHECK_EXPIRATION_TIME:  "* * * * *" #every day "0 1 * * *"
      CHECKEND_EXPIRATION_SEC: '60' #24h 86400
      DOCKER_VERNEMQ_LOG__CONSOLE: "both"
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: "debug"
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS: "on"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_REGISTER__HOOK: "auth_on_register"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_REGISTER__ENDPOINT: "http://webhook-verne:4000/reg"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_PUBLISH__HOOK: "auth_on_publish"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_PUBLISH__ENDPOINT: "http://webhook-verne:4000/pub"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_SUBSCRIBE__HOOK: "auth_on_subscribe"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_SUBSCRIBE__ENDPOINT: "http://webhook-verne:4000/sub"
      #DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_UNSUBSCRIBE__HOOK: "on_unsubscribe"
      #DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_UNSUBSCRIBE__ENDPOINT: "http://webhook:4000/unsub"
      #DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_DELIVER__HOOK: "on_deliver"
      #DOCKER_VERNEMQ_VMQ_WEBHOOKS__DOJOT_DELIVER__ENDPOINT: "http://webhook:4000/deliver"
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT: "0.0.0.0:8883"
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__USE_IDENTITY_AS_USERNAME: "off"
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__REQUIRE_CERTIFICATE: "on"
      DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: /vernemq/cert/ca.crt
      DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: /vernemq/cert/broker.crt
      DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: /vernemq/cert/broker.key
      DOCKER_VERNEMQ_LISTENER__SSL__CRLFILE: /vernemq/cert/ca.crl

  ejbca_simple:
    image: mprevide/ejbca:sec
    ports:
      - 5583:5583
    hostname: localhost
    restart: always

  webhook-verne:
    image: mprevide/webhook_verne
    restart: always
    environment:
      VERNE_WEBHOOKS_PORT: "4000"
      VERNE_WEBHOOKS_LOG_LEVEL: "debug"
