version: '3'
services:
  locust-master:
    image: eduardogmisiuk/dojot-locust
    environment:
      # Don't forget to set the environment variables
      DOJOT_URL: "http://10.202.21.1:8000"
      DOJOT_USER: "admin"
      DOJOT_PASSWD: "admin"
      DOJOT_MQTT_HOST: "10.202.21.1"
      DOJOT_MQTT_PORT: "1883"
      DOJOT_MQTT_TIMEOUT: "60"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWD: ""
      NUMBER_OF_DEVICES: "10"
    command: bash master_entrypoint.sh
    volumes:
      - ..:/usr/src/app
    ports:
      - 8089:8089
      - 5557:5557
    healthcheck:
      test: curl --fail -s http://localhost:8089 || exit 1
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: json-file
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - 6380:6379