version: '3'
services:
  locust-slave:
    image: eduardogmisiuk/dojot-locust
    command: bash slave_entrypoint.sh
    volumes:
      - ..:/usr/src/app
    environment:
      # Don't forget to set the environment variables
      DEBUG_MODE: "False"
      DOJOT_MQTT_HOST: "10.50.11.227"
      # TODO: differentiate DOJOT_MQTT_PORT and DOJOT_MQTTS_PORT variables
      DOJOT_MQTT_PORT: "30011"
      DOJOT_MQTT_TIMEOUT: "120"
      LOCUST_MASTER_HOST: "10.50.11.142"
      LOCUST_LOG_DIR: "logs"
      REDIS_HOST: "10.50.11.142"
      REDIS_PORT: "6380"
      REDIS_PASSWD: ""
      TASK_MIN_TIME: "30000"
      TASK_MAX_TIME: "30000"
