apiVersion: v1
kind: Service
metadata:
  name: ejbca

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: ejbca

  ports:
    - name: http
      port: 5583
      nodePort: 30020

  type: NodePort