apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt-client
  namespace: dojot
spec:
  serviceName: "mqtt-client"
  selector:
    matchLabels:
      app: mqtt-client
  replicas: 4
  template:
    metadata:
      labels:
        app: mqtt-client
    spec:
      containers:
      - name: v2k_bridge
        image: jonaphael/mqtt_client
        env:
        - name: AUTH_URL
          value: "http://auth:5000"
        - name: DATA_BROKER
          value: "http://data-broker"
        - name: DATA_BROKER_DNS
          value: "data-broker"
        - name: DATA_BROKER_PORT
          value: "80"
        - name: KAFKA_HOSTS
          value: "kafka-server:9092"
        - name: DOJOT_MQTT_HOST
          value: "vernemq-k8s"
        - name: DOJOT_MQTT_PORT
          value: "30010"
        - name: CERT_DNS
          value: "mqtt-client"
        - name: CERT_EJBCA_API_BROKER
          value: "ejbca-wrapper"
        - name: CERT_EJBCA_API_PORT
          value: "5583"
