apiVersion: apps/v1
kind: Deployment
metadata:
  name: vernemq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vernemq
  template:
    metadata:
      labels:
        app: vernemq
    spec:
      containers:
      - name: vernemq
        image: eduardogmisiuk/dojot_verne
        ports:
        - containerPort: 1883
          name: mqtt
---
kind: Service
apiVersion: v1
metadata:
  name: vernemq-service
spec:
  type: NodePort
  selector:
    app: vernemq
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: 32321
