apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca-simple
spec:
  selector:
    matchLabels:
      app: ejbca-simple
  replicas: 1
  template: #templates for the pods
    metadata:
      labels:
        app: ejbca-simple
    spec:
      hostname: localhost
      containers:
      - name: ejbca-simple
        image: mprevide/ejbca
        env:
        - name: DATABASE_JDBC_URL
          value: "jdbc:postgresql://postgres-ejbca/ejbca_db"
        - name: DATABASE_USER
          value: "youruser"
        - name: DATABASE_PASSWORD
          value: "yourpassword"
        - name: LOG_LEVEL_APP
          value: "ERROR"
        - name: LOG_LEVEL_SERVER_SUBSYSTEMS
          value: "ERROR"
        - name: LOG_LEVEL_APP_WS_TRANSACTIONS
          value: "ERROR"
        - name: LOG_LEVEL_SERVER
          value: "ERROR"
        - name: LOG_LEVEL_APP_OCSP_TRANSACTIONS
          value: "ERROR"