apiVersion: v1
kind: Service
metadata:
  labels:
    vernemq: k8s
  name: vernemq-k8s
spec:
  ports:
  - name: mqtt
    port: 1883
    targetPort: mqtt
  - name: mqtts
    port: 8883
    targetPort: mqtts
  - name: mqtt-ws
    port: 8080
    targetPort: mqtt-ws
  - name: http
    port: 8888
    targetPort: http
  selector:
    app: vernemq
    vernemq: k8s
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Service
metadata:
  name: vernemq-k8s

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    vernemq: k8s
  
  ports:
    - name: mqtt
      port: 1883
      nodePort: 30010
    - name: mqtts
      port: 8883
      nodePort: 30011
  
  type: NodePort