apiVersion: vernemq.com/v1alpha1
kind: VerneMQ
metadata:
  labels:
    vernemq: k8s
  name: k8s
spec:
  baseImage: mprevide/verne
  env:
    - name: STATIC_CERT
      value: "n"
    - name: K8S_ENV
      value: "y"
    - name: CERT_EJBCA_API_BROKER
      value: "ejbca-simple"
    - name: CERT_EJBCA_API_PORT
      value: "5583"
    - name: CRL_UPDATE_TIME
      value: "* * * * *" #every 10 min "*/10 * * * *"
    - name: CHECK_EXPIRATION_TIME
      value: "* * * * *" #every 10 min "*/10 * * * *"
    - name: CHECKEND_EXPIRATION_SEC
      value: "60" #24h  86400
    - name: CHECKEND_EXPIRATION_SEC
      value: "60" #24h  86400
    - name: CERT_DNS
      value: "10.50.11.235"
    ## BASE-64 config
    - name: VERNEMQ_CONF
      value: "bWV0YWRhdGFfcGx1Z2luID0gdm1xX3N3YwpsaXN0ZW5lci52bXEuY2x1c3RlcmluZyA9ICRNWV9QT0RfSVA6NDQwNTMKbGlzdGVuZXIuaHR0cC5kZWZhdWx0ID0gMC4wLjAuMDo4ODg4CnBsdWdpbnMudm1xX3Bhc3N3ZCA9IG9mZgpwbHVnaW5zLnZtcV9hY2wgPSBvZmYKcGx1Z2lucy52bXFfazhzLnBhdGggPSAvdmVybmVtcS9wbHVnaW5zL19idWlsZC9kZWZhdWx0CnBsdWdpbnMudm1xX2s4cyA9IG9uCmxldmVsZGIubWF4aW11bV9tZW1vcnkucGVyY2VudCA9IDIwCmxvZy5jb25zb2xlID0gY29uc29sZQpwbHVnaW5zLnZtcV93ZWJob29rcz1vbgp2bXFfd2ViaG9va3MuZG9qb3RfcmVnaXN0ZXIuaG9vayA9IGF1dGhfb25fcmVnaXN0ZXIKdm1xX3dlYmhvb2tzLmRvam90X3JlZ2lzdGVyLmVuZHBvaW50ID0gaHR0cDovL3dlYmhvb2stdmVybmU6NDAwMC9yZWcKdm1xX3dlYmhvb2tzLmRvam90X3B1Ymxpc2guaG9vayA9IGF1dGhfb25fcHVibGlzaAp2bXFfd2ViaG9va3MuZG9qb3RfcHVibGlzaC5lbmRwb2ludCA9IGh0dHA6Ly93ZWJob29rLXZlcm5lOjQwMDAvcHViCnZtcV93ZWJob29rcy5kb2pvdF9zdWJzY3JpYmUuaG9vayA9IGF1dGhfb25fc3Vic2NyaWJlCnZtcV93ZWJob29rcy5kb2pvdF9zdWJzY3JpYmUuZW5kcG9pbnQgPSBodHRwOi8vd2ViaG9vay12ZXJuZTo0MDAwL3N1YgpsaXN0ZW5lci5tYXhfY29ubmVjdGlvbnMgPSAyMDAwMDAKbGlzdGVuZXIubnJfb2ZfYWNjZXB0b3JzID0gMTAwCm1heF9pbmZsaWdodF9tZXNzYWdlcyA9IDIwCm1heF9vbmxpbmVfbWVzc2FnZXMgPSAxMDAwMApsaXN0ZW5lci5zc2wuZGVmYXVsdCA9IDAuMC4wLjA6ODg4MwpsaXN0ZW5lci5zc2wuZGVmYXVsdC5jYWZpbGUgPSAgL3Zlcm5lbXEvY2VydC9jYS5jcnQKbGlzdGVuZXIuc3NsLmRlZmF1bHQuY2VydGZpbGUgPSAvdmVybmVtcS9jZXJ0LyRIT1NUTkFNRS5jcnQKbGlzdGVuZXIuc3NsLmRlZmF1bHQua2V5ZmlsZSA9IC92ZXJuZW1xL2NlcnQvJEhPU1ROQU1FLmtleQpsaXN0ZW5lci5zc2wuZGVmYXVsdC5jcmxmaWxlID0gIC92ZXJuZW1xL2NlcnQvY2EuY3JsCmxpc3RlbmVyLnNzbC5kZWZhdWx0LnVzZV9pZGVudGl0eV9hc191c2VybmFtZSA9IG9mZgpsaXN0ZW5lci5zc2wuZGVmYXVsdC5yZXF1aXJlX2NlcnRpZmljYXRlID0gb24="
  config:
    configs:
    - name: allow_register_during_netsplit
      value: "on"
    - name: allow_publish_during_netsplit
      value: "on"
    - name: allow_subscribe_during_netsplit
      value: "on"
    - name: allow_unsubscribe_during_netsplit
      value: "on"
    listeners:
    - address: 0.0.0.0
      port: 1883
    - address: 0.0.0.0
      port: 1888
      websocket: true
    plugins: []
  serviceAccountName: vernemq-k8s
  size: 1
  version: 1.9.0
  tag: latest
