apiVersion: vernemq.com/v1alpha1
kind: VerneMQ
metadata:
  labels:
    vernemq: k8s
  name: k8s
spec:
  baseImage: muhamedavila/vmq_dojot
  env:
      ## BASE-64 config
    - name: CERT_EJBCA_API_BROKER
      value: "ejbca-simple"
    - name: CERT_EJBCA_URL
      value: "5583"
    - name: VERNEMQ_CONF
      value: "bWV0YWRhdGFfcGx1Z2luID0gdm1xX3N3YwpsaXN0ZW5lci52bXEuY2x1c3RlcmluZyA9ICRNWV9QT0RfSVA6NDQwNTMKbGlzdGVuZXIuaHR0cC5kZWZhdWx0ID0gMC4wLjAuMDo4ODg4CnBsdWdpbnMudm1xX3Bhc3N3ZCA9IG9mZgpwbHVnaW5zLnZtcV9hY2wgPSBvbgpwbHVnaW5zLnZtcV9rOHMucGF0aCA9IC92ZXJuZW1xL3BsdWdpbnMvX2J1aWxkL2RlZmF1bHQKcGx1Z2lucy52bXFfazhzID0gb24KbGV2ZWxkYi5tYXhpbXVtX21lbW9yeS5wZXJjZW50ID0gMjAKbG9nLmNvbnNvbGUgPSBjb25zb2xlCnBsdWdpbnMudm1xX3dlYmhvb2tzPW9uCnZtcV93ZWJob29rcy5kb2pvdF9wdWJsaXNoLmhvb2sgPSBvbl9wdWJsaXNoCnZtcV93ZWJob29rcy5kb2pvdF9wdWJsaXNoLmVuZHBvaW50ID0gaHR0cDovL3dlYmhvb2stdmVybmU6NDAwMC9wdWI="
  config:
    configs:
    - name: allow_register_during_netsplit
      value: "on"
    - name: allow_publish_during_netsplit
      value: "on"
    - name: allow_subscribe_during_netsplit
      value: "on"
    - name: allow_unsubscribe_during_netsplit
      value: "on"
    - name: allow_anonymous
      value: "on"
    listeners:
    - address: 0.0.0.0
      port: 1883
    - address: 0.0.0.0
      port: 1888
      websocket: true
    plugins: []
  serviceAccountName: vernemq-k8s
  size: 1
  version: 1.8.0
